// Code generated by protoc-gen-go. DO NOT EDIT.
// source: consignment.proto

package consignment

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Consignment struct {
	Id                   string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Containers           []*Container `protobuf:"bytes,2,rep,name=Containers,proto3" json:"Containers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Consignment) Reset()         { *m = Consignment{} }
func (m *Consignment) String() string { return proto.CompactTextString(m) }
func (*Consignment) ProtoMessage()    {}
func (*Consignment) Descriptor() ([]byte, []int) {
	return fileDescriptor_3804bf87090b51a9, []int{0}
}

func (m *Consignment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Consignment.Unmarshal(m, b)
}
func (m *Consignment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Consignment.Marshal(b, m, deterministic)
}
func (m *Consignment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Consignment.Merge(m, src)
}
func (m *Consignment) XXX_Size() int {
	return xxx_messageInfo_Consignment.Size(m)
}
func (m *Consignment) XXX_DiscardUnknown() {
	xxx_messageInfo_Consignment.DiscardUnknown(m)
}

var xxx_messageInfo_Consignment proto.InternalMessageInfo

func (m *Consignment) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Consignment) GetContainers() []*Container {
	if m != nil {
		return m.Containers
	}
	return nil
}

type Container struct {
	User                 string   `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Container) Reset()         { *m = Container{} }
func (m *Container) String() string { return proto.CompactTextString(m) }
func (*Container) ProtoMessage()    {}
func (*Container) Descriptor() ([]byte, []int) {
	return fileDescriptor_3804bf87090b51a9, []int{1}
}

func (m *Container) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Container.Unmarshal(m, b)
}
func (m *Container) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Container.Marshal(b, m, deterministic)
}
func (m *Container) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Container.Merge(m, src)
}
func (m *Container) XXX_Size() int {
	return xxx_messageInfo_Container.Size(m)
}
func (m *Container) XXX_DiscardUnknown() {
	xxx_messageInfo_Container.DiscardUnknown(m)
}

var xxx_messageInfo_Container proto.InternalMessageInfo

func (m *Container) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

type Response struct {
	Code                 bool         `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Consignment          *Consignment `protobuf:"bytes,2,opt,name=Consignment,proto3" json:"Consignment,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_3804bf87090b51a9, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCode() bool {
	if m != nil {
		return m.Code
	}
	return false
}

func (m *Response) GetConsignment() *Consignment {
	if m != nil {
		return m.Consignment
	}
	return nil
}

func init() {
	proto.RegisterType((*Consignment)(nil), "Consignment")
	proto.RegisterType((*Container)(nil), "Container")
	proto.RegisterType((*Response)(nil), "Response")
}

func init() { proto.RegisterFile("consignment.proto", fileDescriptor_3804bf87090b51a9) }

var fileDescriptor_3804bf87090b51a9 = []byte{
	// 194 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x31, 0x0f, 0x82, 0x30,
	0x10, 0x85, 0x43, 0x35, 0x06, 0x0e, 0xa3, 0xa1, 0x13, 0x71, 0x91, 0x30, 0x11, 0x63, 0x3a, 0xe0,
	0x0f, 0x70, 0x60, 0x72, 0x71, 0x28, 0xbf, 0x00, 0xe1, 0x82, 0x1d, 0x6c, 0x9b, 0xb6, 0xfa, 0xfb,
	0x8d, 0x8d, 0x62, 0xd9, 0xde, 0xbd, 0xef, 0xf2, 0xf2, 0xee, 0x20, 0xeb, 0x95, 0xb4, 0x62, 0x94,
	0x0f, 0x94, 0x8e, 0x69, 0xa3, 0x9c, 0x2a, 0x2f, 0x90, 0x36, 0x7f, 0x93, 0x6e, 0x80, 0x88, 0x21,
	0x8f, 0x8a, 0xa8, 0x4a, 0x38, 0x11, 0x03, 0x3d, 0x00, 0x34, 0x4a, 0xba, 0x4e, 0x48, 0x34, 0x36,
	0x27, 0xc5, 0xa2, 0x4a, 0x6b, 0x60, 0x93, 0xc5, 0x03, 0x5a, 0xee, 0x21, 0x99, 0x26, 0x4a, 0x61,
	0xf9, 0xb4, 0x68, 0xbe, 0x51, 0x5e, 0x97, 0x57, 0x88, 0x39, 0x5a, 0xad, 0xa4, 0xc5, 0x0f, 0xef,
	0xd5, 0x80, 0x9e, 0xc7, 0xdc, 0x6b, 0xca, 0x66, 0x5d, 0x72, 0x52, 0x44, 0x55, 0x5a, 0xaf, 0x59,
	0xe0, 0xf1, 0x70, 0xa1, 0x3e, 0xc3, 0xb6, 0xbd, 0x0b, 0xad, 0x85, 0x1c, 0x5b, 0x34, 0x2f, 0xd1,
	0x23, 0x3d, 0x42, 0xd6, 0x18, 0xec, 0x1c, 0x86, 0x47, 0xcd, 0x22, 0x76, 0x09, 0xfb, 0x95, 0xb8,
	0xad, 0xfc, 0x0f, 0x4e, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x09, 0x3f, 0x3a, 0x85, 0x18, 0x01,
	0x00, 0x00,
}
