// Code generated by protoc-gen-go. DO NOT EDIT.
// source: consignment.proto

package consignment

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Person_PhoneType int32

const (
	Person_MOBILE Person_PhoneType = 0
	Person_HOME   Person_PhoneType = 1
	Person_WORK   Person_PhoneType = 2
)

var Person_PhoneType_name = map[int32]string{
	0: "MOBILE",
	1: "HOME",
	2: "WORK",
}

var Person_PhoneType_value = map[string]int32{
	"MOBILE": 0,
	"HOME":   1,
	"WORK":   2,
}

func (x Person_PhoneType) String() string {
	return proto.EnumName(Person_PhoneType_name, int32(x))
}

func (Person_PhoneType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3804bf87090b51a9, []int{2, 0}
}

type Request struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_3804bf87090b51a9, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Response struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_3804bf87090b51a9, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type Person struct {
	Name                 string                `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                   int32                 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Mail                 string                `protobuf:"bytes,3,opt,name=mail,proto3" json:"mail,omitempty"`
	Numbers              []*Person_PhoneNumber `protobuf:"bytes,4,rep,name=numbers,proto3" json:"numbers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_3804bf87090b51a9, []int{2}
}

func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (m *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(m, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Person) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Person) GetMail() string {
	if m != nil {
		return m.Mail
	}
	return ""
}

func (m *Person) GetNumbers() []*Person_PhoneNumber {
	if m != nil {
		return m.Numbers
	}
	return nil
}

type Person_PhoneNumber struct {
	Number               string           `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	Type                 Person_PhoneType `protobuf:"varint,2,opt,name=type,proto3,enum=Person_PhoneType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Person_PhoneNumber) Reset()         { *m = Person_PhoneNumber{} }
func (m *Person_PhoneNumber) String() string { return proto.CompactTextString(m) }
func (*Person_PhoneNumber) ProtoMessage()    {}
func (*Person_PhoneNumber) Descriptor() ([]byte, []int) {
	return fileDescriptor_3804bf87090b51a9, []int{2, 0}
}

func (m *Person_PhoneNumber) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person_PhoneNumber.Unmarshal(m, b)
}
func (m *Person_PhoneNumber) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person_PhoneNumber.Marshal(b, m, deterministic)
}
func (m *Person_PhoneNumber) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person_PhoneNumber.Merge(m, src)
}
func (m *Person_PhoneNumber) XXX_Size() int {
	return xxx_messageInfo_Person_PhoneNumber.Size(m)
}
func (m *Person_PhoneNumber) XXX_DiscardUnknown() {
	xxx_messageInfo_Person_PhoneNumber.DiscardUnknown(m)
}

var xxx_messageInfo_Person_PhoneNumber proto.InternalMessageInfo

func (m *Person_PhoneNumber) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *Person_PhoneNumber) GetType() Person_PhoneType {
	if m != nil {
		return m.Type
	}
	return Person_MOBILE
}

func init() {
	proto.RegisterEnum("Person_PhoneType", Person_PhoneType_name, Person_PhoneType_value)
	proto.RegisterType((*Request)(nil), "Request")
	proto.RegisterType((*Response)(nil), "Response")
	proto.RegisterType((*Person)(nil), "Person")
	proto.RegisterType((*Person_PhoneNumber)(nil), "Person.PhoneNumber")
}

func init() { proto.RegisterFile("consignment.proto", fileDescriptor_3804bf87090b51a9) }

var fileDescriptor_3804bf87090b51a9 = []byte{
	// 269 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xdd, 0x4a, 0xc3, 0x40,
	0x10, 0x85, 0x9b, 0x9f, 0xa6, 0xc9, 0x14, 0x4a, 0x3a, 0x82, 0x84, 0x62, 0x21, 0x04, 0x94, 0x80,
	0x98, 0x8b, 0xf8, 0x06, 0x42, 0xa1, 0x62, 0x6b, 0xc2, 0x22, 0x78, 0xdd, 0xda, 0x21, 0x06, 0xb2,
	0xbb, 0x31, 0x9b, 0x5e, 0xf4, 0x95, 0x7d, 0x0a, 0xc9, 0x26, 0x15, 0x85, 0xde, 0x7d, 0x3b, 0xdf,
	0xd9, 0x19, 0x38, 0x30, 0xff, 0x90, 0x42, 0x95, 0x85, 0xe0, 0x24, 0xda, 0xa4, 0x6e, 0x64, 0x2b,
	0xa3, 0x25, 0x4c, 0x18, 0x7d, 0x1d, 0x49, 0xb5, 0x88, 0x60, 0x8b, 0x1d, 0xa7, 0xc0, 0x08, 0x8d,
	0xd8, 0x63, 0x9a, 0xa3, 0x1b, 0x70, 0x19, 0xa9, 0x5a, 0x0a, 0x45, 0xe8, 0x83, 0xc5, 0x55, 0x31,
	0xe8, 0x0e, 0xa3, 0x6f, 0x03, 0x9c, 0x9c, 0x1a, 0x25, 0xc5, 0xa5, 0xcf, 0x38, 0x03, 0xb3, 0x3c,
	0x04, 0x66, 0x68, 0xc4, 0x63, 0x66, 0x96, 0x87, 0x2e, 0xc3, 0x77, 0x65, 0x15, 0x58, 0x7d, 0xa6,
	0x63, 0x7c, 0x80, 0x89, 0x38, 0xf2, 0x3d, 0x35, 0x2a, 0xb0, 0x43, 0x2b, 0x9e, 0xa6, 0x57, 0x49,
	0xbf, 0x31, 0xc9, 0x3f, 0xa5, 0xa0, 0x57, 0xed, 0xd8, 0x39, 0xb3, 0xd8, 0xc0, 0xf4, 0xcf, 0x1c,
	0xaf, 0xc1, 0xe9, 0xcd, 0x70, 0x77, 0x78, 0xe1, 0x2d, 0xd8, 0xed, 0xa9, 0x26, 0x7d, 0x7b, 0x96,
	0xce, 0xff, 0xad, 0x7c, 0x3b, 0xd5, 0xc4, 0xb4, 0x8e, 0xee, 0xc1, 0xfb, 0x1d, 0x21, 0x80, 0xb3,
	0xcd, 0x9e, 0x9e, 0x37, 0x2b, 0x7f, 0x84, 0x2e, 0xd8, 0xeb, 0x6c, 0xbb, 0xf2, 0x8d, 0x8e, 0xde,
	0x33, 0xf6, 0xe2, 0x9b, 0xe9, 0x1d, 0x8c, 0xd7, 0x54, 0x55, 0x12, 0x97, 0x60, 0xe7, 0xa5, 0x28,
	0xd0, 0x4d, 0x86, 0xe6, 0x16, 0x5e, 0x72, 0x2e, 0x29, 0x1a, 0xed, 0x1d, 0x5d, 0xec, 0xe3, 0x4f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xd7, 0x9a, 0x1a, 0x7e, 0x6d, 0x01, 0x00, 0x00,
}
